### PR TITLE
Heroku Pipeline Setup

### PR DESCRIPTION
**Pull request by jedkirby**

### CODE REVIEW

**Comment by NigelGreenway** [comment]
@jedkirby Is this ready to be merged or is there still work to be done to it?

**Comment by jedkirby** [comment]
I'll let you be the judge of that, @NigelGreenway .. https://phpwarks-develop-pr-44.herokuapp.com 😜

**Comment by steadweb** [comment]
Icons are missing 😉

**Comment by jedkirby** [comment]
Closing this as it's been inactive for lots of time.

**Pull request closed without merging**
