### PR TITLE
Bug suggesting parking is open till 11pm

### PR DESCRIPTION
**Pull request by steadweb**
From what I recall, I believe parking is open till 10pm.

/cc @NigelGreenway

### CODE REVIEW

**Comment by NigelGreenway** [comment]
Ah, this is in reference for the other car park. I will look into it properly but I think we are right to change it for now as we can add further details later that are more specific.

**Comment by steadweb** [comment]
Thanks @NigelGreenway - I wasn't aware of the other car park. Maybe we can add both?

**Comment by NigelGreenway** [comment]
Agreed. It would be good to eventually mark out both parking areas.

**Comment by NigelGreenway** [comment]
Unless you mean add both now?

**Comment by steadweb** [comment]
Either or, doesn't matter 👍

**Comment by NigelGreenway** [comment]
Happy for this to be merged?  @steadweb 😃

**Pull request merged**
